### last time {.smaller}

*  sandboxing without operating system support
   *  example of WebAssembly
*  full app sandboxing and permission dialogs
   *  avoiding user fatique
   *  having developers understand what permissions to request
   *  unintended consequences of permissions
*  static analysis
   *  compromising by allowing false-positives
   *  approximating possible execution
   *  only tracking information relevant to property being tested

###

### challenge assignment {.smaller}

*  to be released today
*  seven challenge executables; complete any five for full credit
*  make exploit program that either
   *  outputs something we can input to the challenge executable, or
   *  is connected to challenge executable input/output like ROP assignment
*  cause program to output Congratulations message with your name

### challenge assignment help

*  your job to figure out which technique applicable to each one
*  TAs can help you with
   *  generally how you identify what vulnerability/exploit techniques work
   *  how to do those exploits in other examples
*  we will provide example solution to prior assignments
   *  you can use these as a basis for your challenge solutions if you choose


{{< include /static/_talk-uaf-example.qmd >}}

## static analysis limits? {visibility="hidden"}

{{< include /static/_static-limits.qmd >}}

## analysis for common insecure patterns {visibility="hidden"}

{{< include /static/_clang-static-patterns.qmd >}}

{{< include /bounds/_talk-inner.qmd >}}
