
### authenticated pointers (1)


```
some_function:
    authentication_code <- MAC(
        secret key, 
        return address
    )
    ... dangerous function code ...
    assert(authenication_code ==
        MAC(secret key, return address))
    jump to return address
```

*  compute MAC (message authentication code) for return address
*  verify MAC before using it

### authenticated return addresses (1)

*  instead of return address<br/>
   store {return address, MAC(secret key, return address)}
*  check MAC before every return
<hr class="vspace"/>
*  preview: will have hardware help for keeping secret key secret
*  exercise: what can attacker still do with stack overflow?

### authenticated pointers (2)

```
some_function:
    authentication_code <- MAC(
        secret key,
        stack pointer, 
        return address
    )
    ... dangerous function code ...
    assert(authenication_code ==
        MAC(secret key, stack pointer, return address))
    jump to return address
```

### authenticated return addresses (2)


*  instead of return address<br/>
   store {return address, MAC(secret key, <em>stack address</em> return address)}
*  check MAC before every return
<hr class="vspace"/>
*  prevented returning to wrong function...
*  exercise: what can attacker still do?

### storing MACs

*  scheme so far: store extra information alongside address
*  inconvenient: need to allocate extra space for address
   *  pretty easy to do for return addresses...
   *  ... but we'd like to apply this to other things
*  alternate idea:
   *  encode MAC + pointer together in pointer-sized thing
   *  decode to get out original pointer
   *  (probably something that looks more like symmetric encryption)

### authenticated pointers (3)  {.smaller}

```
some_function:
    return address <- encode(
        secret key,
        stack pointer, 
        return address
    )
    ... dangerous function code ...
    return address <- decode_or_crash(
        secret key,
        stack pointer, 
        return address
    )
    jump to return address

```

### authenticated pointers (4)  {.smaller}


```
some_vtable[index] <- encrypt(
    secret key,
    label,
    address of some of function
)
... dangerous code ...
function pointer <- decrypt(
    secret key,
    label,
    object->vtable[index]
)
call function pointer

```

