### last time

*  relocation read-only idea
   *  after dynamic linker fills things in, mark it read-only
   *  conflicts with lazy binding
*  read-only sections
*  address space layout randomization
   *  limits on how random
*  getting multiple tries at guess random value
   *  need for "enough" randomness

### homework Q+A

## kept together: danger of leaks {visibility="hidden"}

{{< include /mitigate-aslr/_aslr-entropy-together.qmd >}}

## info leak {visibility="hidden"}

{{< include /mitigate-aslr/_info-disc-stack-addr-exer.qmd >}}

{{< include /mitigate-aslr/_aslr-leaks.qmd >}}

## exercise: using a leak {visibility="hidden"}

{{< include /mitigate-aslr/_aslr-using-leak-exer.qmd >}}

## exercise: using a leak (2) {visibility="hidden"}

{{< include /mitigate-aslr/_aslr-using-leak-exer2.qmd >}}

# ASLR cost/history {visibility="hidden"}

### why not always ASLR? 

* ASLR seems like no-brainer 
   * have to choose address anyway
   * why not choose at random?
* big problem: performance/code size impacts
* smaller problem: inconsistent behavior when bugs

## Unix PIC history {visibility="hidden"}

{{< include /mitigate-aslr/_unix-pic-history.qmd >}}

## alternate approach: Windows {visibility="hidden"}

{{< include /mitigate-aslr/_aslr-windows-pic.qmd >}}

## changes with position-independent code {visibility="hidden"}

{{< include /mitigate-aslr/_pic-switch-example.qmd >}}

{{< include /mitigate-aslr/_pic-cost-code.qmd >}}

## vtable pointers? {visibility="hidden"}

{{< include /mitigate-aslr/_reloc-vtable.qmd >}}

## PIE / PIC {visibility="hidden"}

{{< include /mitigate-aslr/_pic-options.qmd >}}

{{< include /rop/_talk-inner.qmd >}}

# backup slides

## exercise: without absolute addresses? {visibility="hidden"}

{{< include /mitigate-aslr/_aslr-without-abs-ex.qmd >}}

## PIC cost measurements {visibility="hidden"}

{{< include /mitigate-aslr/_pic-cost-measure.qmd >}}

## PIE / PIC code example

{{< include /mitigate-aslr/_aslr-pie.qmd >}}


###

###

