
### interlude: strace


* <code>strace</code> --- system call tracer 

   * on Linux, some other Unices
   * OS X approx. equivalent: <code>dtruss</code>
   * Windows approx. equivalent: Process Monitor

* indicates what system calls (operating system service requests) used by a program


### statically linked hello.exe  {.smaller}



* `gcc -no-pie -static -o hello-static.exe hello.s`
* `strace ./hello-static.exe`:
 
<pre><code>execve("./hello-static.exe", ["./hello-static.exe"], [/* 46 vars */]) = 0
<span data-fragment-index="2" class="fragment custom myem-only">uname({sysname="Linux", nodename="reiss-lenovo", ...</span>) = 0}
<span data-fragment-index="2" class="fragment custom myem-only">brk(NULL)                               = 0x20a5000</span>
<span data-fragment-index="3" class="fragment custom myem-only">brk(0x20a61c0)                          = 0x20a61c0</span>
<span data-fragment-index="2" class="fragment custom myem-only">arch_prctl(ARCH_SET_FS, 0x20a5880)      = 0</span>
<span data-fragment-index="2" class="fragment custom myem-only">readlink("/proc/self/exe", "/home/cr4bd/spring2017/cs4630/sl"..., 4096) = 62</span>
<span data-fragment-index="2" class="fragment custom myem-only">brk(0x20c71c0)                          = 0x20c71c0</span>
<span data-fragment-index="2" class="fragment custom myem-only">brk(0x20c8000)                          = 0x20c8000</span>
<span data-fragment-index="2" class="fragment custom myem-only">access("/etc/ld.so.nohwcap", F_OK)</span>      = -1 ENOENT (No such file or directory)
<span data-fragment-index="3" class="fragment custom myem-only">fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 1), ...</span>) = 0}
<span data-fragment-index="3" class="fragment custom myem-only">write(1, "Hello, World!\n", 14)         = 14</span>
<span data-fragment-index="4" class="fragment custom myem-only">exit_group(14)</span>                          = ?
+++ exited with 14 +++
</code></pre>

::: {.myoverbox .vlow .fragment .fade-in-then-out fragment-index=2}

uname, arch_prctl, access, brk --- <br />
part of standard library setup (added by compiler)

:::

::: {.myoverbox .vlow .fragment .fade-in-then-out fragment-index=3}

fstat, write --- implementation of puts

:::

::: {.myoverbox .vlow .fragment .fade-in-then-out fragment-index=4}

exit_group --- standard library shutdown

:::
