
### ELF example  {.smaller}



* <code>objdump -x /bin/busybox</code> (on my laptop)
* <code>-x</code>: output all headers
 
<pre><code>/bin/busybox:     file format \\myemphTwo{elf64-x86-64}
/bin/busybox
architecture: i386:x86-64, flags 0x00000102:
EXEC_P, D_PAGED
start address \\myemphThree{0x0000000000402170}

Program Header:
\[...]

Sections:
\[...]
</code></pre>


### a program header (1)  {.smaller}


<pre><code>Program Header:
\[...]
LOAD off    0x0001000 vaddr 0x0401000 paddr 0x0401000 align 2**12
     filesz \\myemphTwo{0x01b04ed} memsz 0x01b04ed flags \\myemphThree{r-x}
\[...]
LOAD off    0x0207950 vaddr 0x0608950 paddr 0x0608950 align 2**12
     filesz \\myemphFour{0x0008f40} memsz \\myemphFour{0x000c718} flags rw-

</code></pre>
 

* load <code>[0x1bd04ed]{.fragment fragment-index=2 .custom .myem-only}</code> bytes ([read+executable]{.fragment fragment-index=3 .custom .myem-only}): 

   * from <code>0x1000</code> bytes into the file
   * to memory at <code>0x401000</code> <br>

* load <code>0x8f40</code> bytes (read+write): 

   * from <code>0x207950</code> bytes into the file
   * to memory at <code>0x608950</code>
   * [plus (<code>0xc718</code>--<code>0x8f40</code>) bytes of zeroes]{.fragment fragment-index=4 .custom .myem-only}



### a program header (2)  {.smaller}


<pre><code>Program Header:
\[...]
    NOTE off    0x0000290 vaddr 0x0400290 paddr 0x0400290 align 2**2
         filesz 0x0000044 memsz 0x0000044 flags r--
     TLS off    0x0207950 vaddr 0x0608950 paddr 0x0608950 align 2**3
         filesz 0x0000030 memsz 0x0000092 flags r--
0x6474e553 off  0x0000270 vaddr 0x0400270 paddr 0x0400270 align 2**3
         filesz 0x0000020 memsz 0x0000020 flags r--
   STACK off    0x0000000 vaddr 0x0000000 paddr 0x0000000 align 2**4
         filesz 0x0000000 memsz 0x0000000 flags rw-
   RELRO off    0x0207950 vaddr 0x0608950 paddr 0x0608950 align 2**0
         filesz 0x00066b0 memsz 0x00066b0 flags r--
\[...]
</code></pre>
 

* NOTE --- comment
* TLS --- thread-local storage region (used via <code>%fs</code>)
* 0x6474e553 --- ‘GNU_PROPERTY’ --- adtl linker/loader info
* STACK --- indicates stack is read/write
* RELRO --- make this read-only after runtime linking

