
### hello.s


```asm
.data
string: .asciz "Hello, World!"
.text
.globl main
main:
    movq $string, %rdi
    call puts
    ret
```


### hello.o (pre-static or dynamic linking) 


<pre><code>SYMBOL TABLE:
0000000000000000 l    d  .text  0000000000000000 .text
0000000000000000 l    d  .data  0000000000000000 .data
0000000000000000 l    d  .bss   0000000000000000 .bss
0000000000000000 l       .data  0000000000000000 string
0000000000000000 <span data-fragment-index="6" class="fragment custom myem-only">g</span>       <span data-fragment-index="7" class="fragment custom myem-only">.text  0000000000000000</span> main
0000000000000000         <span data-fragment-index="2" class="fragment custom myem-only">*UND*  0000000000000000 puts</span>

RELOCATION RECORDS FOR [.text]:
OFFSET           TYPE              VALUE 
<span data-fragment-index="2" class="fragment custom myem-only">0000000000000003</span> <span data-fragment-index="5" class="fragment custom myem-only">R_X86_64_32S</span>      <span data-fragment-index="4" class="fragment custom myem-only">.data</span>
<span data-fragment-index="3" class="fragment custom myem-only">0000000000000008</span> <span data-fragment-index="5" class="fragment custom myem-only">R_X86_64_PC32</span>     <span data-fragment-index="3" class="fragment custom myem-only">puts</span>-0x0000000000000004
</code></pre>

::: {.myoverbox .vlow fragment-index=1 .fragment .fade-in-then-out}

undefined symbol `puts` = look for `puts` elsewhere

:::

::: {.myoverbox .vlow fragment-index=1 .fragment .fade-in-then-out}

relocation for `puts` = <br />
insert address of `puts`-0x4 at byte 8 of .text (code)<br />
(part of machine code for `call puts`)

:::

::: {.myoverbox .vlow fragment-index=2 .fragment .fade-in-then-out}

relocation for `.data` = string location <br />
insert address of string at byte 3 of .text (code)<br />
(part of machine code for `movq $string, %rdi`)

:::

::: {.myoverbox fragment-index=3 .fragment .fade-in-then-out}

different ways to represent address<br />
32S = signed 32-bit value<br />
PC32 = 32-bit different from current address<br />
[(puts-0x4 to make it difference from end of call instead of middle of call)]{.my-small}

:::

::: {.myoverbox .vlow fragment-index=4 .fragment .fade-in-then-out}

`g` = global (used by other files) <br /> `l` = local

:::

::: {.myoverbox .vlow fragment-index=5 .fragment .fade-in-then-out}

`main` at `.text` segments beginning + 0 bytes

:::

### hello.o / statically linked, no PIE  {.smaller}

hello.o: 
<pre><code>Disassembly of section .text:

0000000000000000 &lt;main&gt;:
   0:   48 c7 c7 00 00 00 00    mov    $0x0,%rdi
                        3: R_X86_64_32S .data
   7:   e8 00 00 00 00          call   c &lt;main+0xc&gt;
                        8: R_X86_64_PLT32       puts-0x4
   c:   c3                      ret    
</code></pre>
 <hr />
 hello.exe (gcc -static -no-pie): 
<pre><code>Disassembly of section .text:
...
 00000000004016c3 &lt;main&gt;:
   4016c3:       48 c7 c7 b5 16 40 00    mov    $0x4016b5,%rdi
   4016ca:       e8 e1 a9 00 00          call   40c0b0 &lt;_IO_puts&gt;
   4016cf:       c3                      ret    
...
</code></pre>

