
### dynamically linked hello.exe  {.smaller}



* `gcc -no-pie -o hello.exe hello.s`
* `strace ./hello.exe`:
 
<pre><code>execve("./hello.exe", ["./hello.exe"], [/* 46 vars */]) = 0
<it>...</it>
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=137808, ...}) = 0
<it>...</it>
open(<span data-fragment-index="2" class="fragment custom myem-only">"/lib/x86_64-linux-gnu/libc.so.6"</span>, O_RDONLY|O_CLOEXEC) = 3
<span data-fragment-index="3" class="fragment custom myem-only">read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0&gt;\0\1\0\0\0P\t\2\0\0\0\0\0"..., 832) = 832</span>
fstat(3, {st_mode=S_IFREG|0755, st_size=1864888, ...}) = 0
<span data-fragment-index="4" class="fragment custom myem-only">mmap(NULL, 3967392, PROT_READ|PROT_EXEC, ..., 3, 0) = 0x7fdfee54d000</span>
mprotect(0x7fdfee70c000, 2097152, PROT_NONE) = 0
<span data-fragment-index="5" class="fragment custom myem-only">mmap(0x7fdfee90c000, 24576, PROT_READ|PROT_WRITE, ..., 3, 0x1bf000) = 0x7fdfee90c000</span>
<span data-fragment-index="6" class="fragment custom myem-only">mmap(0x7fdfee912000, 14752, PROT_READ|PROT_WRITE, ..., -1, 0) = 0x7fdfee912000</span>
close(3)                                = 0
<it>...</it>
write(1, "Hello, World!\\n", 14)         = 14
exit_group(14)                          = ?
+++ exited with 14 +++
</code></pre>

::: {.myoverbox .vlow .fragment .fade-in-then-out fragment-index=2}

`libc.so.6` --- contains puts, etc. code<br />
being opened by executable after it starts running

:::

::: {.myoverbox .vlow .fragment .fade-in-then-out fragment-index=3}

code reading from libc.os.6's header<br />
gets contents of all the LOAD directives

:::

::: {.myoverbox .vlow .fragment .fade-in-then-out fragment-index=4}

`mmap`: used to load code/data from library into memory (3 = opened file)

:::

::: {.myoverbox .vlow .fragment .fade-in-then-out fragment-index=5}

`mmap`: used to allocate zero-initialized data segment

:::

