
### sudo exploit 


* this writeup: summary from [https://www.openwall.com/lists/oss-security/2021/01/26/3](https://www.openwall.com/lists/oss-security/2021/01/26/3)
* from group at Qualys


### sudo bug  {.smaller}



* the bug:
 
```c
for (size = 0, av = NewArgv + 1; *av; av++)
     size += strlen(*av) + 1;
if (size == 0 || (user_args = malloc(size)) == NULL) { ... }
...
for (to = user_args, av = NewArgv + 1; (from = *av); av++) {
while (*from) {
  if (from[0] == '\\' && !isspace((unsigned char)from[1]))
    from++;
  *to++ = *from++;
...

```
 

* can skip <code>\0</code> if prefixed with backslash
* but <code>strlen</code> used to allocate buffer
* disagreement about copied string length
* heap overflow!


### brute-forcing? 


* method: tried to lots of buffer overflows, get crashes
* looked at them by hand, found interesting ones…


### one crash  {.smaller}


```
0x000056291a25d502 in process_hooks_getenv (name=name@...ry=0x7f4a6d7dc046 "SYSTEMD_BYPASS_USERDB", value=value@...ry=0x7ffc595cc240) at ../../src/hooks.c:108

=> 0x56291a25d502 <process_hooks_getenv+82>:    callq  *0x8(%rbx)

108         rc = hook->u.getenv_fn(name, &val, hook->closure);

```
 

* they overwrote a function pointer on the heap!
* next inquiry: where did that usually point?


### sudoers.so  {.smaller}


```
    *** interesting standard library function: ***
0000000000008a00 <execv@plt>:
    8a00:      endbr64 
    8a04:      bnd jmpq *0x55565(%rip)        # 5df70 <execv@GLIBC_2.2.5>
    8a0b:      nopl   0x0(%rax,%rax,1)
...
    *** usual value of function pointer: ***
000000000000ea00 <sudoers_hook_getenv>:
    ea00:      endbr64 
    ea04:      xor    %eax,%eax
    ea06:      cmpb   $0x0,0x51d36(%rip)        # 60743 <sudoers_policy@@Base+0x2003>
    ea0d:      jne    eaf8 <freeaddrinfo@plt+0x60a8>
    ea13:      cmpq   $0x0,0x51d45(%rip)        # 60760 <sudoers_policy@@Base+0x2020>

```
 

* observations (that hold true even with ASLR): 

   * addr(<code>execv@plt</code>) - addr(<code>sudoers_hook_getenv</code>) = <code>-0x6000</code>
   * last 12 bits of execv@plt always <code>a00</code> (page alignment)



### changing pointer (part one)  {.smaller}


* suppose hook_getenv pointer is <code>0xabcdef8a00</code> 

   * as bytes: <code><em>00 8a</em> ef cd ab 00 00 00</code>

* then execv@plt pointer is <code>0xabcdef3a00</code> 

   * as bytes: <code><em>00 3a</em> ef cd ab 00 00 00</code>
 
<hr class="vspace" />
* only need to change the last two bytes
* also: same change would work if pointer had different high bits
* only four bits of random data from ASLR!


### changing pointer (part two)  {.smaller}


* solution: guess hook_getenv pointer at  <code>0x</code> (unknown) <code>8a00</code>
* overwrite last two bytes with <code>00 3a</code> 
<hr class="vspace" />
* if right: will execute your program
* if wrong: will crash 
<hr class="vspace" />
* what if crashes? try again!  

   * would work about once every 16 tries…
   * but actual exploit needed to write a 00 byte at the end (strcpy)
   * so worked ‘only’ about once every 4096 tries



### into exploit 


* make <code>SYSTEMD_BYPASS_USERDB</code> program in current directory
* run sudo, triggering buffer overflow to change <br>`sudoers_hook_getenv("SYSTEMD_BYPASS_USERDB", ...)`<br> into <br>`execv("SYSTEMD_BYPASS_USERDB", ...)` 

   * (well, try to change --- it won't always work)


