
### runc bug  {.smaller}

* 2019 bug in Docker, other container implementations (CVE-2019-5736) 
   * blog post for vulnerability finders: <br>[[https://blog.dragonsector.pl/2019/02/cve-2019-5736-escape-from-docker-and.html](https://blog.dragonsector.pl/2019/02/cve-2019-5736-escape-from-docker-and.html)]{.my-small}
<hr class="vspace" />
* bug setup: 
   * user starts malicious container X
   * user tells docker to start a new command in malicious container X
   * [malicious container X hijacks the ‘‘new command’’ starting program]{.fragment fragment-index=2 .custom .myem-only}
   * hijacked program used to access stuff outside container
* part of problem: Docker and others weren't using user namespaces at the time 
   * compatability problems

### setup: /proc/PID  {.smaller}

* Linux provides /proc directory to access info about programs
* used for implementing process list utils, debugging 
   * needed to make a functional container
* subdirectory for each process in current container 
   * process ID PID has /proc/PID subdirectory
   * /proc/self is alias for current process's subdirectory
<hr class="vspace" />
* included is /proc/PID/exe file --- alias for executable file


### running a command in existing container  {.smaller}


* to run command X in existing container: 
<hr class="vspace" />
* step 1: switch current process to that container
* <em>code in container can access /proc here?</em>
* <em>including overwriting /proc/self/exe!</em> 
   * which is a program run as root!
<hr class="vspace" />
* step 2: execute command X


### partial fix  {.smaller}


* can disable access to /proc/PID/exe (and related things)
* system call: <code>prctl(PR_SET_DUMPABLE, 0)</code>
* but… the run-in-container tool did this for a while 
<hr class="vspace" />
* problem: this gets reset on executing a new program
* and attacker could make the new program be /proc/PID/exe 

   * one mechanism: symbolic links (file aliases)

* but change dynamic linking setup to run attacker code
* … which accesses /proc/self/exe


### full fix  {.smaller}


* make single-use copy of start-in-container tool each time command run 

   * in-memory file

* … so modifying it doesn't change anything 

   * (but it's also protected from modification)
 
<hr class="vspace" />
* other solutions: 

   * make executable non-writable (e.g. SELinux, don't run container as root)


