
### SELinux  {.smaller}


* <em>S</em>ecurity <em>E</em>nhanced Linux
* ‘‘Mandatory Access Control’’ system for the Linux 

   * mandatory: can be configured to require enumeration of files programs can access
   * (versus normally: specify what files programs can't access)

* not necessairily run in mandatory control mode 
<hr class="vspace" />
* programs run in particular ‘‘domain’’
* objects (files, port numbers, other programs, etc.) can be assigned labels
* rules about what labels programs are allowed to access


### viewing/assigning labels (1)  {.smaller}


```
$ ls -Z /var/log/lastlog
-rw-r--r--. root root system_u:object_r:lastlog_t:s0   /var/log/lastlog

```
 

* above: default Red Hat Linux/CentOS configuration
* system user
* object role
* lastlog type
 
```
$ chcon --type=newtype_t some_file

```


### assigning labels (2) 



* labels via: ‘‘file context mapping’’
 
```
$ semanage fcontext --add --type web_files_t '/var/www/html(/.*)?'
$ restorecon -R -v /var/www/html

```
 

* pattern matching rules set <i>default</i> labels
* restorecon --- switch to default labels, applying rules


### assigning rules  {.smaller}



* subset of default rules for Apache httpd (webserver):
 
```
define(`read_files_pattern',`
  allow $1 $2:dir search_dir_perms;
  allow $1 $3:file read_file_perms;
')
...
define(`read_lnk_files_pattern',`
  allow $1 $2:dir search_dir_perms;
  allow $1 $3:lnk_file read_lnk_file_perms;
')
...
allow httpd_t httpd_config_t:dir list_dir_perms;
read_files_pattern(httpd_t, httpd_config_t, httpd_config_t)
read_lnk_files_pattern(httpd_t, httpd_config_t, httpd_config_t)

```
 

* httpd_t: ‘type’ for webserver process

