
# principle: least privilege {visibility="hidden"}

{{< include /sandbox/_least-priv.qmd >}}

## what do browsers need? {visibility="hidden"}

{{< include /sandbox/_what-browser-perms.qmd >}}

## OS users {visibility="hidden"}

{{< include /sandbox/_os-users.qmd >}}

## promise: privilege separation {visibility="hidden"}

{{< include /sandbox/_browser-priv-sep-intro.qmd >}}

# privilege separation: video decode {visibility="hidden"}

{{< include /sandbox/_privsep-video-decode.qmd >}}

## another user is not enough {visibility="hidden"}

{{< include /sandbox/_privsep-video-decode-too-much.qmd >}}

## awkwardness of creating a new user {visibility="hidden"}

{{< include /sandbox/_privsep-video-decode-new-userp.qmd >}}

# system calls as OS interface {visibility="hidden"}

{{< include /sandbox/_what-systemcalls.qmd >}}

# definition: sandbox {visibility="hidden"}

{{< include /sandbox/_sandbox-defn.qmd >}}

# Linux system call filtering {visibility="hidden"}

## simple Linux system call filtering {visibility="hidden"}

{{< include /sandbox/_linux-syscall-filter.qmd >}}

# strace /listing system calls {visibility="hidden"}

<!-- FIXME: split, exercise asking what operations to allow/prohibit -->

{{< include /sandbox/_strace-hello.qmd >}}

## more fine-grained filtering? {visibility="hidden"}

{{< include /sandbox/_linux-syscall-filter-delta.qmd >}}

{{< include /sandbox/_linux-syscall-filter-bpf.qmd >}}

## aside: libseccomp {visibility="hidden"}

{{< include /sandbox/_libseccomp.qmd >}}

## problems with filter {visibility="hidden"}

{{< include /sandbox/_linux-syscall-open-filter-hard.qmd >}}

## shared services? {visibility="hidden"}

{{< include /sandbox/_app-confine-shared-services.qmd >}}

## more sophisticated filters {visibility="hidden"}

# Chrome architecture {visibility="hidden"}

{{< include /sandbox/_chrome-arch.qmd >}}

## Site Isolation {visibility="hidden"}

{{< include /sandbox/_chrome-site-isolation.qmd >}}

# OpenSSH architecture {visibility="hidden"}

{{< include /sandbox/_openssh-privsep.qmd >}}

## exercise: priv sep for {visibility="hidden"}

{{< include /sandbox/_priv-sep-for-exer.qmd >}}

## versus capability-type approach {visibility="hidden"}

{{< include /sandbox/_v-cap-approach.qmd >}}

<!-- FIXME: more capability OS slides? -->

## chroot {visibility="hidden"}

{{< include /sandbox/_chroot.qmd >}}

## exercise{visibility="hidden"}

{{< include /sandbox/_chroot-exer.qmd >}}

## Linux namespaces {visibility="hidden"}

{{< include /sandbox/_linux-ns.qmd >}}

## Linux programs that attempt confinement {visibility="hidden"}

{{< include /sandbox/_example-linux.qmd >}}

## containers {visibility="hidden"}

{{< include /sandbox/_containers.qmd >}}

### sandbox escapes generally 

* bug in sandbox interface 
   * example: memory/injection error in handling inputs
* unintended functionality of sandboxed operations


## runC bug{visibility="hidden"}

{{< include /sandbox/_runc-bug.qmd >}}

## Chrome sandbox escapes{visibility="hidden"}

{{< include /sandbox/_chrome-sandbox-escape.qmd >}}


# Which sandboxing? {visibility="hidden"}

{{< include /sandbox/_which-sandbox-exer.qmd >}}

# sandboxing without OS support {visibility="hidden"}

{{< include /sandbox/_no-os-support.qmd >}}

## Wasm {visibility="hidden"}

{{< include /sandbox/_wasm.qmd >}}

# sandboxing API: RLBox {visibility="hidden"}

{{< include /sandbox/_rlbox.qmd >}}

### sandboxing whole applications, revisited

*  couldn't usefully sandbox whole web browswer
   *  needed too much legitimate access to files/network
   *  doesn't protect webpage X from malicious webpage Y if browser is vulnerable
*  but we do actually do whole-application sandboxing
   *  most prominant example: mobile phones

# the Android sandbox {visibility="hidden"}

{{< include /sandbox/_android-sandbox.qmd >}}

## OSX sandboxing {visibility="hidden"}

{{< include /sandbox/_osx-sandbox.qmd >}}

## Qubes {visibility="hidden"}

{{< include /sandbox/_qubes.qmd >}}


# application permissions {visibility="hidden"}

{{< include /sandbox/_app-perms.qmd >}}

### UI problems with application permissions

* do applications request sensible permissions?
* do users pay attention to permission requests?
* do users understand what permissions mean?
* are permissions fine-grained enough?
* are permissions coarse-grained enough?

### UI problems with application permissions

* <em>do applications request sensible permissions?</em>
* do users pay attention to permission requests?
* do users understand what permissions mean?
* are permissions fine-grained enough?
* are permissions coarse-grained enough?

## do request right permissions? {visibility="hidden"}

{{< include /sandbox/_app-perm-right.qmd >}}

### UI problems with application permissions

* do applications request sensible permissions?
* <em>do users pay attention to permission requests?</em>
* <em>do users understand what permissions mean?</em>
* are permissions fine-grained enough?
* are permissions coarse-grained enough?

## do users understand permissions? {visibility="hidden"}

{{< include /sandbox/_app-perm-users.qmd >}}

## how to ask for permission? {visibility="hidden"}

{{< include /sandbox/_app-perm-how.qmd >}}

## permissions abuse: Cloak and Dagger {visibility="hidden"}

{{< include /sandbox/_cloak-and-dagger.qmd >}}

## permissions abuse: information leak {visibility="hidden"}

{{< include /sandbox/_info-leak-reardon.qmd >}}


