
### antivirtualization

* a lot of malware tries to behave different in a VM 
<hr class="vspace" />
* why? 
   * used by antivirus software to handle packers
   * used to analyze malware
   * …


### antivirtualization techniques

* query virtual devices
   * solution: mirror devices of some real machine
* time operations that are slower in VM/emulation
   * solution: virtual clock
* use operations not supported by VM
   * solution: support everything

### antivirtualization techniques

* *query virtual devices*
   * solution: mirror devices of some real machine
* time operations that are slower in VM/emulation
   * solution: virtual clock
* use operations not supported by VM
   * solution: support everything

### virtual devices 


* VirtualBox device drivers?
* VMware-brand ethernet device?
* …

### antivirtualization techniques

* query virtual devices
   * solution: mirror devices of some real machine
* *time operations that are slower in VM/emulation*
   * solution: virtual clock
* use operations not supported by VM
   * solution: support everything

### slower operations

* not-"native" VM: 
   * everything is really slow
* otherwise --- trigger ‘‘callbacks’’ to VM implementation: 
   * system calls?
   * allocating and accessing memory?
* … and hope it's reliably slow enough

### antivirtualization techniques

* query virtual devices
   * solution: mirror devices of some real machine
* time operations that are slower in VM/emulation
   * solution: virtual clock
* *use operations not supported by VM*
   * solution: support everything

### operations not supported

* missing instructions kinds? 
   * FPU instructions
   * MMX/SSE instructions
   * undocumented (!) CPU instructions

* network access

* [not handling OS features?]{.fragment .myem .custom fragment-index=1}
   * setting up special handlers for segfault
   * multithreading
   * system calls that make callbacks
   * …

::: {.myoverbox .fragment fragment-index=1}

often want to use virtual machine not running real operating system<br />
and/or without access to normal set of files<br />
means we'll almost certainly miss OS features

:::
