
# Rust {visibility="hidden"}

## aside: why do people like C/C++? {visibility="hidden"}

{{< include /betterpl/_why-ccpp.qmd >}}

## safety + escape hatch {visibility="hidden"}

{{< include /betterpl/_safe-plus-escape-hatch.qmd >}}

{{< include /betterpl/_java-escape-hatch.qmd >}}

## general philosophy {visibility="hidden"}

{{< include /betterpl/_rust-general.qmd >}}

## general syntax (1) {visibility="hidden"}

{{< include /betterpl/_rust-syntax-basic.qmd >}}

## vectors in Rust {visibility="hidden"}

{{< include /betterpl/_rust-syntax-vec.qmd >}}

## functions for types {visibility="hidden"}

{{< include /betterpl/_rust-syntax-impl.qmd >}}

## references {visibility="hidden"}

## basic example{visibility="hidden"}

{{< include /betterpl/_rust-refs.qmd >}}

## in context{visibility="hidden"}

{{< include /betterpl/_rust-ex-with-refs.qmd >}}

## references in structs {visibility="hidden"}

{{< include /betterpl/_rust-ex-with-refs-struct.qmd >}}

## basic ownership {visibility="hidden"}

<!-- FIXME: fixup overlay pictures for errors -->

{{< include /betterpl/_rust-ownership.qmd >}}

## exercise {visibility="hidden"}

{{< include /betterpl/_rust-ownership-exer.qmd >}}

## single owner rule issue {visibility="hidden"}

{{< include /betterpl/_rust-owner-rule-limit.qmd >}}

# Rust: stopping dangling pointers {visibility="hidden"}

### rules to stop dangling pointers  {.smaller}

* [objects have an single <i>owner</i>]{.fragment .custom .myem-only fragment-index=1}
* [owner can give away ownership permanently]{.fragment .custom .myem-only fragment-index=2}
   * object is ‘‘moved’’
* [owner can let someone borrow object temporarily]{.fragment .custom .myem-only fragment-index=3}
   * allows us to give away reference to object
   * track as if object temporarily moved
   * need to know how long object is borrowed for
* can borrow object for reading while others also reading
   * don't need to force exclusive owner/borrower of object
   * need to distinguish mutable and immutable borrowing
* only modify object when exactly one user 
   * owner or exclusive borrower

## borrowing (simple) {visibility="hidden"}

{{< include /betterpl/_rust-borrowing.qmd >}}


## exercise {visibility="hidden"}

{{< include /betterpl/_rust-no-dangle-rules-apply.qmd >}}

## borrowing (multiple readers) {visibility="hidden"}

### rules to stop dangling pointers  {.smaller}

* objects have an single <i>owner</i>
* owner can give away ownership permanently
   * object is ‘‘moved’’
* owner can let someone borrow object temporarily
   * allows us to give away reference to object
   * track as if object temporarily moved
   * need to know how long object is borrowed for
* <em>can borrow object for reading while others also reading</em>
   * don't need to force exclusive owner/borrower of object
   * need to distinguish mutable and immutable borrowing
* only modify object when exactly one user 
   * owner or exclusive borrower

{{< include /betterpl/_rust-borrowing-2read.qmd >}}

## Rust lifetimes {visibility="hidden"}

### rules to stop dangling pointers  {.smaller}

* objects have an single <i>owner</i>
* owner can give away ownership permanently
   * object is ‘‘moved’’
* owner can let someone borrow object temporarily
   * allows us to give away reference to object
   * track as if object temporarily moved
   * <em>need to know how long object is borrowed for</em>
* can borrow object for reading while others also reading
   * don't need to force exclusive owner/borrower of object
   * need to distinguish mutable and immutable borrowing
* only modify object when exactly one user 
   * owner or exclusive borrower

{{< include /betterpl/_why-lifetimes.qmd >}}

## lifetime tracking{visibility="hidden"}

{{< include /betterpl/_rust-lifetimes.qmd >}}

## one writer {visibility="hidden"}

### rules to stop dangling pointers (v 2)  {.smaller}

* objects have an single <i>owner</i>
* owner can give away ownership permanently
   * object is ‘‘moved’’
* owner can let someone borrow object temporarily
   * allows us to give away reference to object
   * track as if object temporarily moved
   * need to know how long object is borrowed for
* can borrow object for reading while others also reading
   * don't need to force exclusive owner/borrower of object
   * need to distinguish mutable and immutable borrowing
* <em>only modify object when exactly one user</em>
   * owner or exclusive borrower

{{< include /betterpl/_rust-borrowing-mut.qmd >}}

{{< include /betterpl/_rust-borrowing-mut-loop.qmd >}}

# destructors {visibility="hidden"}

{{< include /betterpl/_rust-auto-drop.qmd >}}

# Rust: escape hatches and supporting dynamic allocation {visibility="hidden"}

{{< include /betterpl/_dynamic-alloc-basic.qmd >}}

## escape hatches implementing Vec {visibility="hidden"}

{{< include /betterpl/_rust-escape-inside-vec.qmd >}}

## raw pointers {visibility="hidden"}

{{< include /betterpl/_rust-raw-pointers.qmd >}}

## implementing new sharing schemes {visibility="hidden"}

## Rc{visibility="hidden"}

{{< include /betterpl/_rust-impl-rc.qmd >}}

## non-Rust smart pointers {visibility="hidden"}

{{< include /betterpl/_cpp-smart-pointer.qmd >}}

## RefCell{visibility="hidden"}

{{< include /betterpl/_rust-impl-refcell.qmd >}}

## aside: concurrency + UAF {visibility="hidden"}

{{< include /uaf/_linux-conc-uaf.qmd >}}

## concurrency {visibility="hidden"}

{{< include /betterpl/_rust-concurrency.qmd >}}

# aside: other language enforcement? {visibility="hidden"}

{{< include /betterpl/_other-things-lang-enforce.qmd >}}

## other Rust smart pointers {visibility="hidden"}

{{< include /betterpl/_other-rust-smartptr.qmd >}}

## exercise: smart pointer use case {visibility="hidden"}

{{< include /betterpl/_which-smartptr-exer.qmd >}}

## Rust linked list {visibility="hidden"}

{{< include /betterpl/_rust-ll.qmd >}}

# zero-overhead {visibility="hidden"}

{{< include /betterpl/_zero-overhead-p.qmd >}}

# aside: other language enforcement? {visibility="hidden"}

{{< include /betterpl/_other-things-lang-enforce.qmd >}}

## example: constant time languages {visibility="hidden"}

{{< include /betterpl/_fact.qmd >}}
