
### vulnerabilities  {.smaller}


* for viruses, worms
* for trojans + PUP that do more than is supposed to do be allowed 

   * e.g. getting location information without ‘‘permission’’
 

* software <em>vulnerability</em> 

* unintended program behavior <br> that can be used by an adversary


### vulnerability example 


* website able to install software without prompting
* <em>not intended</em> behavior of web browser


### software vulnerability classes (1)  {.smaller}


* <em>memory safety</em> bugs 

   * problems with pointers
   * big topic in this course

* ‘‘injection’’ bugs --- <em>type confusion</em>  

   * commands/SQL within name, label, etc.

* integer overflow/underflow
* …


### software vulnerability classes (2)  {.smaller}


* not checking inputs/permissions 

   * \\url{http://webserver.com/../../../../file-I-shouldn't-get.txt}

* almost any ‘‘undefined behavior’’ in C/C++
* synchronization bugs: time-to-check to time-of-use
* … more?


### vulnerability versus exploit 


* exploit --- something that uses a vulnerability to do something
* proof-of-concept --- something = demonstration the exploit is there 

   * example: open a calculator program


