### pointer leak pattern

*  suppose A and B overlapping
*  if we choose the right A and B:
   *  pointer in A located where data in B is
   *  often can "legitimately" output non-pointer value from B

### information leak example 1  {.smaller}

::::: {.columns}

:::: {.column}

```c
struct Cart {
    int date;
    int num_items;
    ...
    ...
};
```
::::

:::: {.column}

```c
struct String {
    char * buffer;

    size_t size;
};
```

::::

:::::

* setup:
  * trick code into making dangling pointer to Cart
  * trick code into allocating String in same memory 
* then: read `buffer` address by reading date, num_items from Cart
* exercise if Cart date = 591751049 (0x23456789), num_items = 4:
  * what is buffer address?


### information leak example 2  {.smaller}

::::: {.columns}

:::: {.column}


| String |
|--------|
| buffer |
| size |

```c
struct String {
    char *buffer;
    size_t size;
};
```
::::

:::: {.column}

| 

| PNGImage|
|--------|
| vtable pointer |
| ...  |

```cpp
class PNGImage : public Image { ...
public:
    virtual Pixel getPixel(int x, int y, int z);
    ...
};
```

::::

:::::

* setup:
  * trick code into making dangling pointer to String
  * trick code into allocating PNGImage in same space
* then output String to read PNGImage Vtable

### information leak 2 exercise {.smaller}
::::: {.columns}

:::: {.column}


| String |
|--------|
| buffer |
| size |

```c
struct String {
    char *buffer;
    size_t size;
};
```
::::

:::: {.column}

| 

| PNGImage|
|--------|
| vtable pointer |
| ...  |

```cpp
class PNGImage : public Image { ...
public:
    virtual Pixel getPixel(int x, int y, int z);
    ...
};
```

::::

:::::

* exercise:
  * if buffer starts `XFGz\0\0\0\0\0` (0x58, 0x46, 0x47, 0x7a, 0x0, ...)
  * and PNGImage::getPixel in objdump at 0x14658
  * and PNGImage VTable in objdump at 0x13658
  * and strlen GOT pointer in objdump at 0x12444
  * what is strlen GOT pointer address?
