
# use-after-free {visibility="hidden"}

{{< include /uaf/_heap-use-after-free.qmd >}}

## pattern {visibility="hidden"}

### use-after-free type confusion

* pointer to struct A used as struct B
<hr class="vspace">
* some applications:
* [information leak]{.fragment .myem-only .custom}
* arbitrary read/write 
* code execution 

{{< include /uaf/_example-info-leak.qmd >}}

### use-after-free type confusion

* pointer to struct A used as struct B
<hr class="vspace">
* some applications:
* information leak
* <em>arbitrary memory read/write</em>
* code execution 

{{< include /uaf/_example-arb-read-write.qmd >}}

### use-after-free type confusion

* pointer to struct A used as struct B
<hr class="vspace">
* some applications:
* information leak
* arbitrary memory read/write
* <em>code execution</em>

{{< include /uaf/_example-code-exec.qmd >}}

## exercise: info leak {visibility="hidden"}

{{< include /uaf/_heap-uaf-exer-info.qmd >}}

## exercise: subterfuge {visibility="hidden"}

{{< include /uaf/_heap-uaf-exer-subter.qmd >}}

## exercise: vtable {visibility="hidden"}

{{< include /uaf/_heap-uaf-exer.qmd >}}

## reuse observation {visibility="hidden"}

{{< include /uaf/_heap-reuse.qmd >}}

## concurrency and UAF {visibility="hidden"}

{{< include /uaf/_linux-conc-uaf.qmd >}}

## consistency? {visibility="hidden"}

{{< include /uaf/_heap-use-after-free-consistent.qmd >}}

## example {visibility="hidden"}

{{< include /uaf/_heap-use-after-free-chrome.qmd >}}

## JS and similar interfaces v use-after-free {visibility="hidden"}

{{< include /uaf/_heap-use-after-free-js.qmd >}}
