
### handling I/O  {.smaller}


* so far: showed function arguments being variables
* often: want to handle I/O 
<hr class="vspace" />
* idea: track contents of files like arrays in memory 

   * bytes of file can be symbolic (expressions)
   * read/write operations use/modify these arrays

* want to test different inputs 

   * initialize virtual file to fixed contents



### angr: symbolic input  {.smaller}


```
# array of 5000 symbolic bytes named in_0, in_1, ...
input_chars = [claripy.BVS('in_{}'.format(i), 8) for i in range(5000)]
the_input = claripy.Concat(*input_chars)

# setup symbolic execution state with stdin being this file
st = p.factory.full_init_state(...,
    stdin=angr.SimFileStream(name='stdin', content=the_input, has_end=True),
)
...

```
 

* simulation runs copying symbolic values when stdin is read
* then, find a specific state, solve for <em><i>a</i></em> possible value 

   * (0 = Linux ‘file descriptor’ for stdin; 1 = stdout)

 
```
print("stdin", some_state.posix.dumps(0))
print("stdout", some_state.posix.dumps(1))

```


### angr and virtual files  {.smaller}


* angr: two ways to intercept file operations
* one: intercept system calls (requests to OS) 

   * means very Linux-specific and very Windows-specific code
   * one gets()/fgets()/etc. operation often turns into many system calls

* two: replace libc functions with ‘symbolic’ versions 

   * faster
   * doesn't work in statically linked programs
   * won't detect issues resulting from libc details
   * (example: leftover uninitalized values)



### example: other libc interception  {.smaller}


```
class memcpy(angr.SimProcedure):
  def run(self, dst_addr, src_addr, limit):
    if not self.state.solver.symbolic(limit):
        conditional_size = self.state.solver.eval(limit)
    else:
      # constraints on the limit are added during the store
      max_memcpy_size = self.state.libc.max_memcpy_size
      max_limit = self.state.solver.max_int(limit)
      min_limit = self.state.solver.min_int(limit)
      conditional_size = min(max_memcpy_size, max(min_limit, max_limit))
      ...
    ...
    # simplified 
    src_mem = self.state.memory.load(src_addr, conditional_size, endness="Iend_BE")
    self.state.memory.store(dst_addr, src_mem, size=conditional_size, endness="Iend_BE")

    return dst_addr

```
 

* approximation --- choosing specific size

