
### running example  {.smaller}


```
int array[2];
int foo(int x, int y){
    array[x] = 0x10;
    array[y] = 0x20;
    return array[x] + array[y];
}

```
 

* exercise: possible return values?


### in angr (0)  {.smaller}


```
p = angr.Project('mem-demo.so', load_options={'auto_load_libs': False})
x = claripy.BVS('x', 31).zero_extend(1) # 0 sign bit + [31 unknown bits]
y = claripy.BVS('y', 31).zero_extend(1) # 0 sign bit + [31 unknown bits]
foo_func = p.loader.find_symbol('foo').rebased_addr
foo_prototype = angr.sim_type.SimTypeFunction(
    args=(angr.sim_type.SimTypeInt(), angr.sim_type.SimTypeInt()),
    returnty=angr.sim_type.SimTypeInt()
)
st = p.factory.call_state(foo_func, x, y, prototype=foo_prototype)
st.add_constraints(x >= 0, x < 2, y >= 0, y < 2)
sm = p.factory.simulation_manager(st, save_unconstrained=True)
sm.explore()
print(sm)
    # <SimulationManager with 1 deadended>
print(sm.deadended[0].regs.eax)
    # <BV32 0x40>

```


### in angr (0): warnings  {.smaller}


```
WARNING  | The program is accessing register with an unspecified value.
           This could indicate unwanted behavior.
WARNING  | angr will cope with this by generating an unconstrained symbolic variable
           and continuing. You can resolve this by:
WARNING  | 1) setting a value to the initial state
WARNING  | 2) adding the state option ZERO_FILL_UNCONSTRAINED_{MEMORY,REGISTERS}, 
              to make unknown regions hold null
WARNING  | 3) adding the state option SYMBOL_FILL_UNCONSTRAINED_{MEMORY,REGISTERS},
              to suppress these messages.
WARNING  | Filling register 76 with 4 unconstrained bytes referenced from 0x4010fd
           (foo+0x4 in mem-demo.so (0x10fd))
WARNING  | Filling register 68 with 4 unconstrained bytes referenced from 0x401107
           (foo+0xe in mem-demo.so (0x1107))

```


### in angr (0b)  {.smaller}


```
p = angr.Project('mem-demo.so', load_options={'auto_load_libs': False})
x = claripy.BVS('x', 31).zero_extend(1)
y = claripy.BVS('y', 31).zero_extend(1)
foo_func = p.loader.find_symbol('foo').rebased_addr
foo_prototype = angr.sim_type.SimTypeFunction(
    args=(angr.sim_type.SimTypeInt(), angr.sim_type.SimTypeInt()),
    returnty=angr.sim_type.SimTypeInt()
)
st = p.factory.call_state(foo_func, x, y, prototype=foo_prototype,
    add_options=[
        angr.options.SYMBOL_FILL_UNCONSTRAINED_MEMORY,
        angr.options.SYMBOL_FILL_UNCONSTRAINED_REGISTERS,
    ]
)
st.add_constraints(x < 2, y < 2)
sm = p.factory.simulation_manager(st, save_unconstrained=True)
sm.explore()
print(sm)
    # <SimulationManager with 1 deadended>
print(sm.deadended[0].regs.eax)
    # <BV32 0x40>

```


### what's angr doing?  {.smaller}


```
...
print(sm.deadended[0].solver.min(x))
    # 1
print(sm.deadended[0].solver.max(x))
    # 1
print(sm.deadended[0].solver.min(y))
    # 1
print(sm.deadended[0].solver.max(y))
    # 1

```
 

* problem: angr's default memory write strategy: use maximum possible value for address
* compromise: <br> often close enough <br> simplifies work for equation solver dramatically <br> often allows avoiding symbolic execution for much faster emulation


### requesting symbolic addressing (1)  {.smaller}


```
st = p.factory.call_state(foo_func, x, y, prototype=foo_prototype,
    add_options=[
        angr.options.SYMBOL_FILL_UNCONSTRAINED_MEMORY,
        angr.options.SYMBOL_FILL_UNCONSTRAINED_REGISTERS,
        angr.options.SYMBOLIC_WRITE_ADDRESSES, # ****** ADDED ******
    ]
)
...
print(sm.deadended[0].regs.eax)

```
 \\hrulefill{} 
```
<BV32 0x20 + (if x_0_31 == 0x1 then (if y_1_31 == 0x1 then 0x20 else
(if x_0_31 == 0x1 then 0x10 else 0x2)) else (if x_0_31 == 0x0 then
(if y_1_31 == 0x0 then 0x20 else (if x_0_31 == 0x0 then 0x10 else 0x1))
else 0xc0deb4be))>

```


### requesting symbolic addressing (2)  {.smaller}


```
<BV32 0x20 + (if x_0_31 == 0x1 then (if y_1_31 == 0x1 then 0x20 else
(if x_0_31 == 0x1 then 0x10 else 0x2)) else (if x_0_31 == 0x0 then
(if y_1_31 == 0x0 then 0x20 else (if x_0_31 == 0x0 then 0x10 else 0x1))
else 0xc0deb4be))>

```
 \\hrulefill{} 

* 0x20 +  

   * if x==1: 

      * if y == 1: 0x20
      * if x == 1: 0x10
      * else [impossible]: 0x2 (original array value)

   * if x==0: 

      * if y == 0: 0x20
      * if x == 0: 0x10
      * else [impossible]: 0x1 (original array value)




### with more possibilities 


```
int array[30] = { ... }

```
 
```
...
st.add_constraints(x < 30, y < 30) # instead of x < 2, y < 2
...

```
 

* result: much bigger expression…


### even more possibilities  {.smaller}


```
...
st.add_constraints(x < 100, y < 100) # instead of x < 2, y < 2
...

```
 

* problem: angr doesn't consider all possibilities for write by default if more than 128 bytes worth
* so: select a new set of strategies
 
```
st.memory.write_strategies = [
    angr.concretization_strategies.SimConcretizationStrategyRange(4 * 100),
    angr.concretization_strategies.SimConcretizationStrategyMax()
]
st.memory.read_strategies = ... # similar

```
 

* when accessing memory, consider results of:
* a range of up 400 bytes of possibilities <i>OR</i>
* the maximum possible value


### speed changes (with slow install of angr)  {.smaller}


* just loading file + setting up: about 1.6 s
* x \< 2, y \< 2: around 2.0 s (0.4 s of work)
* x \< 30, y \< 30: around 2.2 s (0.6 s of work)
* x \< 100, y \< 100: around 2.6 s (1.0 s of work)
* x \< 200, y \< 200: around 4.3 s (2.9 s of work)
* x \< 300, y \< 300: around 6.5 s (4.9 s of work)
* x \< 400, y \< 400: around 9.4 s (7.8 s of work)

