
### symbolic execution  {.smaller}

* have an emulator/virtual machine
* but represent input values as <i>symbolic variables</i>
   * like in algebra

* choose a path through the program, track <i>constraints</i>
   * create tree of possible paths
* then solve constraints based on variables to create real test case 

{{< include /symbolic/_symbolic-exec-setup.qmd >}}


## examples {visibility="hidden"}

### symbolic execution  {.smaller}

* have an emulator/virtual machine
* <em>but represent input values as <i>symbolic variables</i></em>
   * like in algebra

* choose a path through the program, track <i>constraints</i>
   * create tree of possible paths
* then solve constraints based on variables to create real test case 

{{< include /symbolic/_symbolic-exec-example0.qmd >}}

### actually doing this 

* multiple tools out there, will look at two
<hr class="vspace">
* <em>angr</em> is a binary analysis toolkit written in Python 
   * has Ghidra-like GUI, but not very stable/maintained as far as I can tell
   * among other things, converts assembly into intermediate form
   * supports interactive simulation of program
* <em>KLEE</em> works on LLVM (clang) bytecode
   * generates set of test cases covering all paths
   * cannot analyze code not specially compiled

{{< include /symbolic/_symbolic-exec-example0-angr.qmd >}}

{{< include /symbolic/_symbolic-exec-example0-klee.qmd >}}

### symbolic execution  {.smaller}

* have an emulator/virtual machine
* but represent input values as <i>symbolic variables</i>
   * like in algebra

* <em>choose paths through the program, track <i>constraints</i></em>
   * create tree of possible paths
* then solve constraints based on variables to create real test case 

{{< include /symbolic/_symbolic-exec-example1.qmd >}}

{{< include /symbolic/_symbolic-exec-example1-angr.qmd >}}

{{< include /symbolic/_symbolic-exec-example1-klee.qmd >}}

{{< include /symbolic/_symbolic-exec-example2.qmd >}}

## aside: symbolic exec abstraction {visibility="hidden"}

{{< include /symbolic/_symbolic-exec-abstract.qmd >}}

## concolic {visibility="hidden"}

{{< include /symbolic/_symbolic-aside.qmd >}}

## with pointers {visibility="hidden"}

### handling pointers {.smaller}

*  pointers/references are a challenge
*  simple case: keep track of what each pointer points to in each path...

{{< include /symbolic/_symbolic-exec-example-ptr.qmd >}}

## exercise {visibility="hidden"}

<!-- FIXME: earlier exercise? -->

{{< include /symbolic/_symbolic-exec-exer.qmd >}}

## solving equations?? {visibility="hidden"}

{{< include /symbolic/_solving-equation-p.qmd >}}

## summary: tricky problems with symbolic execution {visibility="hidden"}

{{< include /symbolic/_symbolic-exec-tricky-sum.qmd >}}

# dealing with pointers {visibility="hidden"}

{{< include /symbolic/_symbolic-readwritep.qmd >}}

{{< include /symbolic/_symbolic-varmem-example.qmd >}}

# libc optimization {visibility="hidden"}

{{< include /symbolic/_angr-libc.qmd >}}

# finding overflows examples {visibility="hidden"}

{{< include /symbolic/_angr-find-oflow.qmd >}}

# performance problems {visibility="hidden"}

{{< include /symbolic/_symb-perf.qmd >}}
