### last time

*  integer overflow/underflow bugs
   *  issues with "wrap around"
   *  attacker can choose `big` so `(int)(x * big)` is small
   *  compilers stripping some integer overflow checks
*  randomized testing idea
   *  security bugs $\sim$ crashes
   *  (or we can make them usually crashes)
   *  try lots of things, look for crash

### assignment Q+A

###


## some practical issues {visibility="hidden"}

### fuzzing challenges 

* isolation --- reproducibility, handling crashes/etc.
* speed
* finding useful tests


## isolation {visibility="hidden"}

### fuzzing challenges 

* <em>isolation --- reproducibility, handling crashes/etc.</em>
* speed
* finding useful tests

{{< include /testing/_fuzzing-isolation.qmd >}}

## speed {visibility="hidden"} 

### fuzzing challenges 

* isolation --- reproducibility, handling crashes/etc.
* <em>speed</em>
* finding useful tests

{{< include /testing/_fuzzing-speed.qmd >}}

## lots of bad tests?{visibility="hidden"}

### fuzzing challenges 

* isolation --- reproducibility, handling crashes/etc.
* speed
* <em>finding useful tests</em>

{{< include /testing/_lots-of-bad-tests.qmd >}}

## example: Yang et al{visibility="hidden"}

{{< include /testing/_example-csmith.qmd >}}

## what makes good tests? {visibility="hidden"}

### fuzzing so far

*  "black box" approaches 
   *  "blind" changes to input
   *  using documentaiton of input format
   *  don't require us to understand anything about how program works
*  alternate idea: take advantage of having the code

{{< include /testing/_brainstorm-what-tests.qmd >}}

# metric: coverage {visibility="hidden"}

{{< include /testing/_max-coveragep.qmd >}}

# coverage-guided fuzzing {visibility="hidden"}

{{< include /testing/_coverage-fuzzing.qmd >}}

## examples {visibility="hidden"}

{{< include /testing/_coverage-fuzzing-example.qmd >}}

## exercise {visibility="hidden"}

{{< include /testing/_coverage-fuzzing-exer.qmd >}}

## AFL as running example {visibility="hidden"}

{{< include /testing/_afl.qmd >}}

## automatic test case simplification {visibility="hidden"}

{{< include /testing/_autosimplify.qmd >}}

{{< include /testing/_example-creduce.qmd >}}

### upcoming assignment

*  `indent` utility
   *  takes C program, reformats it
   *  original version used sandboxing, so anything you find probably not exploitable
*  run under AFL++
   *  enable AddressSanitizer to make crashes more consistent
   *  find some crashes
*  diagnose those crashes
   *  figure out what the bugs actually are

## AFL: test template support {visibility="hidden"}

{{< include /testing/_afl-test-templates.qmd >}}

## cmplog

{{< include /testing/_cmplog.qmd >}}

## whiter boxes {visibility="hidden"}

{{< include /testing/_whiter-box-preview.qmd >}}

{{< include /symbolic/_talk-inner.qmd >}}
