
### exercise: cavity finding difficulty?  {.smaller}


* exercise: which is least, most difficult kind of cavity  to <it>write code</it> to find 

* A. gaps between segments
* B. space added for alignment between instructions
* C. unused space in headers


### exercise: scheme for finding alignment space  {.smaller}

example unused space: <pre><code>  404a01:	c3                   	retq   
  <em>404a02:	0f 1f 40 00          	nopl   0x0(%rax)</em>
  <em>404a06:	66 2e 0f 1f 84 00 00 	nopw   %cs:0x0(%rax,%rax,1)</em>
  <em>404a0d:	00 00 00 </em>
</code></pre>
 

* suppose a virus scanned the executable for this pattern of bytes (c3 0f 1f …) <br> to find a cavity
* for compiler generated code, which are likely causes of false positive? 

   * A. <code>c3</code> might be part of non-ret instruction
   * B. <code>ret</code> might return to byte immediately after (0x404a02 in example)
   * C. some other instruction might jump to one of the bytes after
   * D. the entire sequence could be part of the program's data <br> (if the virus didn't check that it was in the text section)


