
# self-replicating malware, generally {visibility="hidden"}

{{< include /virus/_self-repl-mal.qmd >}}

# virus: hide in existing programs {visibility="hidden"}

## motivation {visibility="hidden"}

{{< include /virus/_hide-existing.qmd >}}

## early prevalance/motivations {visibility="hidden"}

{{< include /virus/_early-prevalence.qmd >}}

# case study: Vienna {visibility="hidden"}

{{< include /virus/_vienna-intro.qmd >}}

## aside: COM files {visibility="hidden"}

{{< include /exec-encoding/_com-files.qmd >}}

## entry/exit {visibility="hidden"}

{{< include /virus/_entry-exit.qmd >}}

### Vienna: infection outline

* Vienna appends code to infected application 
<hr class="vspace" />
* <em>where does it read the code come from?</em>
* how is code adjusted for new location in the binary?
   * what linker would do
* how does it keep files from getting infinitely long?

## aside: quines{visibility="hidden"}

{{< include /virus/_quine.qmd >}}

## Vienna replication code{visibility="hidden"}

{{< include /virus/_vienna-replicate.qmd >}}

## Vienan relocation code {visibility="hidden"}

### Vienna: infection outline

* Vienna appends code to infected application 
<hr class="vspace" />
* where does it read the code come from?
* <em>how is code adjusted for new location in the binary?</em>
   * what linker would do
* how does it keep files from getting infinitely long?

## Vienna's relocation code{visibility="hidden"}

{{< include /virus/_vienna-relocate.qmd >}}

## alternate: PIC{visibility="hidden"}

{{< include /virus/_vienna-alt-relocate.qmd >}}

## avoiding reinfection {visibility="hidden"}

### Vienna: infection outline

* Vienna appends code to infected application 
<hr class="vspace" />
* where does it read the code come from?
* how is code adjusted for new location in the binary?
   * what linker would do
* <em>how does it keep files from getting infinitely long?</em>

{{< include /virus/_vienna-reinfect.qmd >}}

# viruses: where to put code {visibility="hidden"}

{{< include /virus/_where-code-intro.qmd >}}

## replacing executables? {visibility="hidden"}

### where to put code: options 

* one <i>or more</i> of:
* <em>replacing executable code</em>
* after executable code (Vienna)
* in unused executable code
* inside OS code
* in memory
* replace existing code

{{< include /virus/_where-code-replace.qmd >}}

## appending/compressing {visibility="hidden"}

{{< include /virus/_where-append-compress.qmd >}}

## cavaties {visibility="hidden"}

### where to put code: options

* one <i>or more</i> of:
* replacing executable code
* after executable code (Vienna)
* <em>in unused executable code</em>
* inside OS code
* in memory
* replace existing code

{{< include /virus/_where-cavaties.qmd >}}

### other empty space

* unused dynamic linking structure
* unused space between segments
* unused debugging/symbol table information?
* unused header space  
   * file offsets of segments can be in middle of header
   * loader doesn't care what segments ‘‘mean’’

## dynamic linking cavaities {visibility="hidden"}

### other empty space

* <em>unused dynamic linking structure</em>
* unused space between segments
* unused debugging/symbol table information?
* unused header space
   * file offsets of segments can be in middle of header
   * loader doesn't care what segments "mean"


{{< include /virus/_where-cavaties-dynamic.qmd >}}


## chaining cavaties (CIH case study){visibility="hidden"}

{{< include /virus/_where-cavaties-chain.qmd >}}

## segment rounding{visibility="hidden"}

### other empty space

* unused dynamic linking structure
* <em>unused space between segments</em>
* unused debugging/symbol table information?
* unused header space  
   * file offsets of segments can be in middle of header
   * loader doesn't care what segments "mean"

{{< include /virus/_where-cavaties-rounding.qmd >}}

## boot sector {visibility="hidden"}

### where to put code: options

* one <i>or more</i> of:
* replacing executable code
* after executable code (Vienna)
* in unused executable code
* <em>inside OS code</em>
* in memory
* replace existing code

{{< include /virus/_where-boot-sector.qmd >}}

## memory residence {visibility="hidden"}

### where to put code: options

* one <i>or more</i> of:
* replacing executable code
* after executable code (Vienna)
* in unused executable code
* inside OS code
* <em>in memory</em>
* replace existing code

{{< include /virus/_residence.qmd >}}

# virus: getting code invoked {visibility="hidden"}

### invoking virus code: options


* boot loader
* change starting location
* alternative approaches: "entry point obscuring"
* edit code that's going to run anyways
* replace a function pointer
* …

## changing start location {visibility="hidden"}

### invoking virus code: options

* boot loader
* <em>change starting location</em>
* alternative approaches: "entry point obscuring"
* edit code that's going to run anyways
* replace a function pointer
* …

{{< include /virus/_invoke-start.qmd >}}

## overwrite existing code {visibility="hidden"}

### invoking virus code: options

* boot loader
* change starting location
* alternative approaches: "entry point obscuring"
* <em>edit code that's going to run anyways</em>
* replace a function pointer
* …

{{< include /virus/_invoke-overwrite-existing.qmd >}}

## using dynamic linking features {visibility="hidden"}

### invoking virus code: options

* boot loader
* change starting location
* alternative approaches: "entry point obscuring"
* edit code that's going to run anyways
* <em>replace a function pointer</em>
* …

{{< include /virus/_invoke-dynamic.qmd >}}

# virus summary? {visibility="hidden"}

{{< include /virus/_summary.qmd >}}
