### last time

*  comparsion logging
   *  working backwards from comparisons to changing inputs
*  symbolic execution
   *  representing values as algebraic variables
   *  write expression of value at end
   *  add constraints for each code path
   *  solve for inputs that satisfy constraints

### quiz Q1 {.smaller}

```c
struct AllocInfo {
    long size_and_free;
    AllocInfo *next_free;
    AllocInfo *prev_free;
}

```
<hr>
```c
region->prev_free->next_free = region->next_free;
region->next_free->prev_free = region->prev_free;
```

*  500 bytes from beginning of string: `size_and_free` (of unalloc'd region)
*  508 bytes from beginning of string: `next_free` (X)
   *  will write to `next_free->prev_free` AKA X + 16
*  516 bytes from beginning of string: `prev_free` (Y)
   *  will write to `prev_free->next_free` AKA Y + 8


### quiz Q2

*  remove-from-linked-list operation edits both PREV and NEXT
*  means we can't point to read-only memory
*  means we can't use '10' as a pointer

{{< include /symbolic/_symbolic-exec-example1.qmd >}}

{{< include /symbolic/_symbolic-exec-example1-angr.qmd >}}

## concolic {visibility="hidden"}

{{< include /symbolic/_symbolic-aside.qmd >}}

## with pointers {visibility="hidden"}

### handling pointers {.smaller}

*  pointers/references are a challenge
*  simple case: keep track of what each pointer points to in each path...

{{< include /symbolic/_symbolic-exec-example-ptr.qmd >}}

## exercise {visibility="hidden"}

{{< include /symbolic/_symbolic-exec-exer.qmd >}}

# dealing with pointers {visibility="hidden"}

{{< include /symbolic/_symbolic-readwritep.qmd >}}

{{< include /symbolic/_symbolic-varmem-example.qmd >}}

# finding overflows examples {visibility="hidden"}

{{< include /symbolic/_angr-find-oflow.qmd >}}

# performance problems {visibility="hidden"}

{{< include /symbolic/_symb-perf.qmd >}}

{{< include /sandbox/_talk-inner.qmd >}}

### backup slides

{{< include /symbolic/_symbolic-exec-example1-klee.qmd >}}

{{< include /symbolic/_symbolic-exec-example2.qmd >}}


## summary: tricky problems with symbolic execution {visibility="hidden"}

{{< include /symbolic/_symbolic-exec-tricky-sum.qmd >}}

## solving equations?? {visibility="hidden"}

{{< include /symbolic/_solving-equation-p.qmd >}}
