### last time

*  what is privilege separation potentially good for?
   *  identifying dangerous tasks to isolate
   *  finding likely to be non-vulnerable interface
*  capability-style permissions
   *  control what things can be named
*  chroot
   *  location of root directory (`/`) depends on process

### assignment Q+A

### quiz Q2, option B

* if (a < b * 3) --- alpha < beta * 3
  * a += b --- a = alpha + beta
* if (a < b * 3) --- alpha + beta < beta * 2

### quiz Q5 (1) {.smaller}
 
* privilege separation limits possible effect of exploit
* SQL injection --- primary concern is accessing things in database at wrong time
  * when injection happens, will still read/change database unless we've limited access to part of the database
    * web application probably wouldn't work if we did that
    * e.g. can probably access _all_ hashed passwords
  * yes, might stop if database has a way of running programs/etc. (but is that really what the attacker wants to do)

### quiz Q5 (2) {.smaller}

* failing to verify access
  * if it could show the information, privilege separation won't change whether it can
  * best privilege separation might do is move/formalize verifying step (e.g. to monitor of sandboxed process)
* integer overflow
  * likely result is buffer oveflow --- probably arbitrary code exection
  * privilege separation will limit impact of that

## Linux namespaces {visibility="hidden"}

{{< include /sandbox/_linux-ns.qmd >}}

## Linux programs that attempt confinement {visibility="hidden"}

{{< include /sandbox/_example-linux.qmd >}}

## containers {visibility="hidden"}

{{< include /sandbox/_containers.qmd >}}

### sandbox escapes generally 

* bug in sandbox interface 
   * example: memory/injection error in handling inputs
* unintended functionality of sandboxed operations


## runC bug{visibility="hidden"}

{{< include /sandbox/_runc-bug.qmd >}}

## Chrome sandbox escapes{visibility="hidden"}

{{< include /sandbox/_chrome-sandbox-escape.qmd >}}

# the Android sandbox {visibility="hidden"}

{{< include /sandbox/_android-sandbox.qmd >}}

## OSX sandboxing {visibility="hidden"}

{{< include /sandbox/_osx-sandbox.qmd >}}

## Qubes {visibility="hidden"}

{{< include /sandbox/_qubes.qmd >}}

# Which sandboxing? {visibility="hidden"}

{{< include /sandbox/_which-sandbox-exer.qmd >}}

# sandboxing without OS support {visibility="hidden"}

{{< include /sandbox/_no-os-support.qmd >}}

## Wasm {visibility="hidden"}

{{< include /sandbox/_wasm.qmd >}}

# sandboxing API: RLBox {visibility="hidden"}

{{< include /sandbox/_rlbox.qmd >}}

# application permissions {visibility="hidden"}

{{< include /sandbox/_app-perms.qmd >}}

### UI problems with application permissions

* do applications request sensible permissions?
* do users pay attention to permission requests?
* do users understand what permissions mean?
* are permissions fine-grained enough?
* are permissions coarse-grained enough?

### UI problems with application permissions

* <em>do applications request sensible permissions?</em>
* do users pay attention to permission requests?
* do users understand what permissions mean?
* are permissions fine-grained enough?
* are permissions coarse-grained enough?

## do request right permissions? {visibility="hidden"}

{{< include /sandbox/_app-perm-right.qmd >}}

### UI problems with application permissions

* do applications request sensible permissions?
* <em>do users pay attention to permission requests?</em>
* <em>do users understand what permissions mean?</em>
* are permissions fine-grained enough?
* are permissions coarse-grained enough?

## do users understand permissions? {visibility="hidden"}

{{< include /sandbox/_app-perm-users.qmd >}}

## how to ask for permission? {visibility="hidden"}

{{< include /sandbox/_app-perm-how.qmd >}}

## permissions abuse: Cloak and Dagger {visibility="hidden"}

{{< include /sandbox/_cloak-and-dagger.qmd >}}

## permissions abuse: information leak {visibility="hidden"}

{{< include /sandbox/_info-leak-reardon.qmd >}}

{{< include /static/_talk-inner.qmd >}}

### backup slides

## chroot {visibility="hidden"}

{{< include /sandbox/_chroot.qmd >}}

## exercise{visibility="hidden"}

{{< include /sandbox/_chroot-exer.qmd >}}
