### last time {.smaller}

*  executable format
   *  directives about what to load + start location
   *  dynamic linker "interpreter" in other file
*  linking
    *  symbol table
*  started: reverse engineering tools
    *  finding strings
    *  looking at libraries
    *  mess-ups with missing symbols

### missing piece

*  talked about execution-generation-time linking
*  mentioned dynamic linking had some extra stuff going on
*  saw example last time --- let's do more detail

### finding library call uses  {.smaller}

[ <code>objdump --disassemble --dyanmic-reloc:</code>]{.my-small} 
```
0000000000005b00 <setuid@plt>:
    5b00:▶      f3 0f 1e fa          ▶  endbr64␣
    5b04:▶      f2 ff 25 fd d3 02 00 ▶  bnd jmp *0x2d3fd(%rip) 
			# 32f08 <setuid@GLIBC_2.2.5>
    5b0b:▶      0f 1f 44 00 00       ▶  nopl   0x0(%rax,%rax,1)

```
 … 
```
   2764f:▶      e8 ec e3 fd ff       ▶  call   5a40 <open@plt>
   27654:▶      89 05 fe 48 01 00    ▶  mov    %eax,0x148fe(%rip)        # 3bf58 <LINES@NCURSES6_TINFO_5.0.19991023+0x5244>
   2765a:▶      31 c0                ▶  xor    %eax,%eax
   2765c:▶      e8 2f e1 fd ff       ▶  call   5790 <getuid@plt>
   27661:▶      89 c7                ▶  mov    %eax,%edi
   27663:▶      31 c0                ▶  xor    %eax,%eax
   27665:▶      e8 96 e4 fd ff       ▶  call   5b00 <setuid@plt>
   2766a:▶      31 c0                ▶  xor    %eax,%eax
   2766c:▶      e8 cf e2 fd ff       ▶  call   5940 <getgid@plt>
   27671:▶      48 83 c4 08          ▶  add    $0x8,%rsp

```


{{< include /exec-encoding/_talk-dl-extra.qmd >}}

# disassembly, need for xrefs {visibility="hidden"}

{{< include /re-tools/_where-is-code.qmd >}}

# cross-references {visibility="hidden"}

{{< include /re-tools/_xrefs.qmd >}}

# high-level overviews {visibility="hidden"}

## function callers/callees {visibility="hidden"}

{{< include /re-tools/_function-call-callee.qmd >}}

## control flow graphs {visibility="hidden"}

{{< include /re-tools/_func-graphs.qmd >}}

## arrows on the side {visibility="hidden"}

{{< include /re-tools/_side-arrows.qmd >}}

# decompiling {visibility="hidden"}

## decompiler {visibility="hidden"}

{{< include /re-tools/_decomp-ex.qmd >}}

## Ghidra: intermediate representation {visibility="hidden"}

{{< include /re-tools/_ghidra-ir.qmd >}}

# patching things {visibility="hidden"}

{{< include /re-tools/_patch.qmd >}}

# on/with debuggers {visibility="hidden"}

{{< include /re-tools/_debuggers.qmd >}}

{{< include /re-tools/_reverse-debug.qmd >}}

# on emulators {visibility="hidden"}

{{< include /re-tools/_emu.qmd >}}

## some higher-level tools {visibility="hidden"}

{{< include /re-tools/_qiling.qmd >}}

{{< include /re-tools/_panda-re.qmd >}}

# reverse engineering tools {visibility="hidden"}

{{< include /x8664-encoding/_talk-inner.qmd >}}

{{< include /virus/_talk-inner.qmd >}}

# backup slides {visibility="hidden"}

### backup slides 

{{< include /exec-encoding/_talk-backup.qmd >}}
