### efficiency of finding new coverage {.smaller}

*  PNG files have chunks with 4-byte type labels
*  parser code something like:

```c
uint32_t image_chunk_type;
fread(&image_chunk_type, 4, 1, image_file);
...
if (image_chunk_type == CHUNK_TYPE_PALETTE) {
    ...
}
```

*  if we make random changes to 512-byte PNG image, how long
   till we enter that if statement?
   *  need to randomly chnage 4 bytes containing "chunk type"
   *  need to randomly choose CHUNK_TYPE_PALETTE
   *  (or have CHUNK_TYPE_PALETTE in "dictionary")

### comparison logging idea

*  instead of just looking at coverage, 
   look at what comparisons run
*  figure out which input matters for comparison this way


### comparison log example {.smaller}

```c
void foo(unsigned a, unsigned b, unsigned c) {
    if (a != 0) { // (1)
        b -= c; // W
    }
    if (b < 5) { // (2)
        if (a > c) { // (3)
            a += b; // X
        }
        b += 4; // Y
    } else {
        a += 1; // Z
    }
    assert(a + b != 7);  // (4)
}
```

<style>.cmptrue {background-color: rgb(230, 255, 230); border: 1px solid rgb(50, 100, 50); }</style>

|input|comparisons|
|-----|-----------|
| a=0, b=0, c=0 | 0 != 0, [0 < 5]{.cmptrue}, 0 > 0, [4 != 7]{.cmptrue} |
| a=1, b=0, c=0 | [1 != 0]{.cmptrue}, [0 < 5]{.cmptrue}, [1 > 0]{.cmptrue}, [5 != 0]{.cmptrue} |
| a=0, b=1, c=0 | 0 != 0, [1 < 5]{.cmptrue}, 0 > 0, [5 != 0]{.cmptrue} |
| a=0, b=0, c=1 | 0 != 0, [0 < 5]{.cmptrue}, [0 > 1]{.cmptrue}, [4 != 0]{.cmptrue} |
: {.collines}

### using comparison logging: exercise (1) {.smaller}

<style>.cmptrue {background-color: rgb(230, 255, 230); border: 1px solid rgb(50, 100, 50); }</style>

|input|comparisons|
|-----|-----------|
| a=0, b=0, c=0 | [0 < 100]{.cmptrue}, 0 == 0x1234 |
| a=1, b=0, c=0 | [1 < 100]{.cmptrue}, 0 == 0x1235 |
| a=2, b=0, c=0 | [2 < 100]{.cmptrue}, 0 == 0x1236 |
| a=0, b=1, c=0 | [0 < 100]{.cmptrue}, 0 == 0x1244 |
| a=0, b=2, c=0 | [0 < 100]{.cmptrue}, 0 == 0x1254 |
| a=0, b=0, c=1 | [0 < 100]{.cmptrue}, 1 == 0x1334 |
| a=0, b=0, c=2 | [0 < 100]{.cmptrue}, 2 == 0x1334 |
: {.collines}

*  exercise 1: If I want to make the first comparison true, what should I change from a=0,b=0,c=0?
*  exercise 2: If I want to make the second comparison true, what should I change from a=0,b=0,c=0?

### using comparison logging: exercise (2) {.smaller}

::: {style="font-size: 90%"}

|input|comparisons|
|-|-----------|
| `aaaaaaaa` | `0x61616161 == 0xDEADFF`, `0x61616161 == 0x12345678`, `'a' == '#'` |
| `baaaaaaa` | `0x62616161 == 0xDEADFF`, `0x61616162 == 0x12345678`, `'b' == '#'` |
| `caaaaaaa` | `0x63616161 == 0xDEADFF`, `0x61616163 == 0x12345678`, `'c' == '#'` |
| `abaaaaaa` | `0x61626161 == 0xDEADFF`, `0x61616261 == 0x12345678`, `'a' == '#'` |
| `acaaaaaa` | `0x61636161 == 0xDEADFF`, `0x61616361 == 0x12345678`, `'a' == '#'` |
| `aabaaaaa` | `0x61616261 == 0xDEADFF`, `0x61626161 == 0x12345678`, `'a' == '#'` |
| `aacaaaaa` | `0x61616361 == 0xDEADFF`, `0x61636161 == 0x12345678`, `'a' == '#'` |
| `aaabaaaa` | `0x61616162 == 0xDEADFF`, `0x62616161 == 0x12345678`, `'a' == '#'` |
| `aaacaaaa` | `0x61616163 == 0xDEADFF`, `0x63616161 == 0x12345678`, `'a' == '#'` |

:::

*  exercise: good new test cases?


### "colorization"

*  try changing all parts of input
*  identify which parts affect which comparisons
   *  called "colorization"
   *  color bytes of input based on which comparisoins they correspond tog
*  more sophisticated ideas:
   *  figure out where number in comparison comes from
   *  figure out likely encoding of number in input
