
# Summary {visibility="hidden"}

### web security summary (1)  {.smaller}


* browser as OS: 

   * websites are like programs

* cross-site scripting 

   * command injection for the web
   * not just stuff to display --- program code for website
   * problem: runs with website permissions (e.g. cookies)



### web security summary (2)  {.smaller}


* isolation mechanism: same origin policy 

   * decision: everything on domain name is ‘‘the same’’

* cross-site request forgery 

   * consequence of statelessness
   * <em>all requests</em> send cookie (password-equivalent)
   * extra token to distinguish ‘‘user initiated’’ or not



# User Tracking {visibility="hidden"}

### on user tracking  {.smaller}


* embedding one web page in another enables tracking users across website
* example: multiple webpages include <code>iframe</code> with a google ad 

   * your browser sends request <em>to Google with same cookie</em>
   * Google reliably gets excerpt of web history

* reason: websites cooperated with Google
* users often don't like this
* what can browsers do about this?


### changing the cookie policy (1)  {.smaller}


* idea: no ‘‘third-party’’ cookies
* only send cookies for URL in address bar 
<hr class="vspace" />
* now embedded Google calendar can't use my credentials
* what about websites that use multiple domains?


### changing the cookie policy (2) 


* by default: don't send cookies on embedded cross-origin requests
* varying ideas about restricting third-party cookies


### third-party cookie restrictions  {.smaller}


* Firefox: 

   * separate ‘cookie jar’ for each top-level domain
   * tracker.com loaded from foo.com != tracker.com loaded from bar.com
   * [heuristics to avoid breaking some websites]{.fragment fragment-index=2 .custom .myem-only}

* Safari 

   * don't see third-party cookies
   * opt-in to separate cookie jar?

* Chrome: 

   * opt-in to partitioned cookie jar



### tracking without cookies  {.smaller}


* websites can do tracking even with no cookies 

   * information in URLs --- add <code>?sessionID</code> to all links
   * web page caches

* websites can ‘‘fingerprint’’ browser and machine 

   * version, fonts, screen resolution, plugins, graphics features, …
   * [caching]{.fragment fragment-index=2 .custom .myem-only} of previously downloaded resources
   * almost unique a surprising amount of the time

* have IP addresses, too --- very good hints


# Web Frameworks {visibility="hidden"}

### Web Frameworks  {.smaller}


* tools for making writing interactive websites help
* e.g. Django (Python):  

   * default to anti-embedding HTTP header (no clickjacking)
   * default to HttpOnly cookies
   * default to requiring CSRF token for POSTs

* usually provide ‘‘templates’’ which escape HTML properly by default 

   * template: `<p>Name: {{name}}` (placeholder in {{…}})
   * if name is `<script>...` result is `<p>Name: &lt;script&gt;...`



# client security {visibility="hidden"}

### recall: UAF triggering code  {.smaller}



* earlier in semester: exploit in Chrome <em>browser</em> itself
 <!-- \lstset{
    language=JavaScript,
    style=smaller,
    moredelim={**[is][\btHL<2|handout:0>]{~2~}{~end~}},
    moredelim={**[is][\btHL<3-4|handout:0>]{~3~}{~end~}},
    moredelim={**[is][\btHL<4|handout:0>]{~4~}{~end~}},
} -->
 
<pre><code>// in HTML near this JavaScript:
// &lt;video id="vid"&gt; (video player element)
function source_opened() {
  buffer = ms.addSourceBuffer('video/webm; codecs="vorbis,vp8"');
  <span data-fragment-index="2" class="fragment custom myem-only">vid.parentNode.removeChild(vid);</span>
  gc(); // force garbage collector to run now
  // garbage collector frees unreachable objects
  // (would be run automatically, eventually, too)
  // buffer now internally refers to delete'd player object
  [[buffer.timestampOffset = 42;]{.fragment fragment-index=3 .custom .myem-only}]{.fragment fragment-index=4 .custom .myem-only}
}
ms = new WebKitMediaSource();
ms.addEventListener('webkitsourceopen', source_opened);
vid.src = window.URL.createObjectURL(ms);
</code></pre>


### browsers and exploits 


* browsers are in a particularly dangerous position for exploits
* <em>routinely run untrusted code</em> (JavaScript on websites)
* huge amounts of code, often written in C/C++ 

   * WebKit (part of Chrome, Safari) has millions of lines of code



### malvertising 


* could trick user into visiting your website 
<hr class="vspace" />
* or pay for ad --- embed your webpage in another! 

   * can run whatever script you like



### modern advertising landscape (1)  {.smaller}


* website ads are often <em>sold in realtime</em>
* conceptual idea: <em>mini-auction</em> for every ad
* major concerns about fraud 

   * are you really showing my ad?

* ad operators want to do own tracking 

   * get better idea what to show/bid



### modern advertising landscape (2)  {.smaller}


* website operators <em>typically don't host ads</em> 

   * don't build own realtime auction infrastructure
   * not trusted to report number of ad views correctly

* ads often sold indirectly 

   * middleman handles bidding/etc.
   * website operators sell to multiple ad operators


