
### dependencies between segments (1)  {.smaller}


```
$ objdump -x foo.exe
...
LOAD off    0x0000000000000000 vaddr 0x0000000000000000 paddr 0x0000000000000000 align 2**12
     filesz 0x0000000000000620 memsz 0x0000000000000620 flags r--
LOAD off    0x0000000000001000 vaddr 0x0000000000001000 paddr 0x0000000000001000 align 2**12
     filesz 0x0000000000000205 memsz 0x0000000000000205 flags r-x
LOAD off    0x0000000000002000 vaddr 0x0000000000002000 paddr 0x0000000000002000 align 2**12
     filesz 0x0000000000000150 memsz 0x0000000000000150 flags r--
LOAD off    0x0000000000002db8 vaddr 0x0000000000003db8 paddr 0x0000000000003db8 align 2**12
     filesz 0x000000000000025c memsz 0x0000000000000260 flags rw-

```
 

* 4 seperately loaded segments: can we choose random addresses for each?


### dependencies between segments (2)  {.smaller}


<pre><code>0000000000001050 &lt;__printf_chk@plt&gt;:
    1050:       f3 0f 1e fa             endbr64 
    1054:       f2 ff 25 75 2f 00 00    bnd jmpq *<em>0x2f75(%rip)        # 3fd0</em> &lt;__printf_chk@GLIBC_2.3.4&gt;
    105b:       0f 1f 44 00 00          nopl   0x0(%rax,%rax,1)
</code></pre>
 

* dependency from 2nd LOAD (0x1000-0x1205) to 4th LOAD (0x3db8-0x4018)
* uses relative addressing rather than linker filling in address


### dependencies between segments (3)  {.smaller}


<pre><code>0000000000001060 &lt;main&gt;:
    1060:       f3 0f 1e fa             endbr64 
    1064:       50                      push   %rax
    1065:       8b 15 a5 2f 00 00       mov    0x2fa5(%rip),%edx        # 4010 &lt;global&gt;
    106b:       48 8d 35 92 0f 00 00    lea    <em>0xf92(%rip)</em>,%rsi        # 2004 &lt;_IO_stdin_used+0x4&gt;
    1072:       31 c0                   xor    %eax,%eax
    1074:       bf 01 00 00 00          mov    $0x1,%edi
    1079:       e8 d2 ff ff ff          callq  1050 &lt;__printf_chk@plt&gt;
</code></pre>
 

* dependency from 2nd LOAD (0x1000-0x1205) to 3rd LOAD (0x2000-0x2150)
* uses relative addressing rather than linker filling in address


### why is this done? 


* Linux made a choice: <br> no editing code when loading programs, libraries 
<hr class="vspace" />
* allows same code to be loaded in multiple processes


### danger of leaking pointers 


* any stack pointer? know everything on the stack!
* any pointer within executable? know everything in the executable!
* any pointer to a particular library? know everything in library!

